### ISSUE TITLE
Origin story?

### ISSUE THREAD

**Issue by amiller** [FiloSottile/powersoftau#1]
Thanks for this awesome contribution, I've been really hoping to see an independent implementation of the Powers of Tau code.

You mentioned in your [public debut](https://lists.z.cash.foundation/pipermail/zapps-wg/2018/000225.html) at the zapps-wg mailing list that you were sponsored by Zcash Co. Could you share some details here about how that worked?

**Comment by FiloSottile** [comment]
Hi Andrew, happy to provide some background.

For context, I am in between jobs and doing casual cryptography engineering contracting while I wait for my visa. I also have been following the Zcash team and work for a while.

When I read of Powers of Tau in December I wanted to play with it and implement it in Go. Even more after reading some criticism on Twitter of the previous MPC ceremony of the likes of "the code is a SPoF". At this point I had no contact with the Zcash team about it.

However, that would have taken time away from consulting, so I figured I would ask the Zcash team if they were interested in paying me to work on it. I spoke with a Zcash team member at CCC and they agreed. I ended up working on it in early January and at RWC, also getting some help from a Zcash team member to understand the Rust implementation.

I was hoping to do a truly clean room implementation, but verification relies on the implementation details of the Rust code in how it hashes to G2. I have anyway verified everything I ported from the other codebase (see #3).

Let me know if this answers your question!
